### ISSUE TITLE
error when compiling for mips-unknown-linux-musl (to run on an OpenWRT device)

### ISSUE THREAD

**Issue by steveej** [opensource-3d-p/rperf#2]
hey :wave:

looks like not all `Atomic...` types are available for this target

```
$ cargo build --release --target mips-unknown-linux-musl
(...)
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
  --> src/client.rs:22:37
   |
22 | use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
   |                                     ^^^^^^^^^
   |                                     |
   |                                     no `AtomicU64` in `sync::atomic`
   |                                     help: a similar name exists in the module: `AtomicU8`
```

**Comment by flan** [comment]
If it's not a 64-bit platform, that makes sense: as far as I know, Rust's atomic operations need to be able to guarantee completion with a single CPU instruction.

I'll see if I can reduce that to something smaller and more universally supported, maybe by using it to store offsets relative to a start-time immutable, rather than a full 64-bit timestamp.

It looks like anything targeting generic MIPS will be able to support 32-bit operations, so I'll start with that, but won't get around to it until tomorrow.

**Comment by flan** [comment]
A change has been pushed that removes use of atomic u64.

The new approach is a mutable 64-bit float, which is a little less-efficient (especially on platforms without native hardware support for processing such things), but since it's just one value that only gets checked about once per second after testing is complete anyway, it shouldn't have any real negative impact.

**Comment by steveej** [comment]
> it's just one value that only gets checked about once per second after testing is complete anyway, it shouldn't have any real negative impact.

thank you for that. it reads like a side effect that is insignificant enough to introduce for the sake of increasing compatibility! thank you :raised_hands:
